server:
  port: 8080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: product_service
            uri: lb://product-service
            predicates:
              - Path=/products/**
          - id: category_service
            uri: lb://category-service
            predicates:
              - Path=/categories/**
eureka:
  client:
    serviceUrl:
#      defaultZone: http://service-registry:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

